//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BDSender.dih_webserv {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DIHPMPFWebserviceSoap11Binding", Namespace="http://webservice.pmpf.dih.com")]
    public partial class DIHPMPFWebservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback wardDictOperationCompleted;
        
        private System.Threading.SendOrPostCallback pharmacyDictOperationCompleted;
        
        private System.Threading.SendOrPostCallback inpOrderCompletionNotifyOperationCompleted;
        
        private System.Threading.SendOrPostCallback staffDictOperationCompleted;
        
        private System.Threading.SendOrPostCallback outpOrderCompletionNotifyOperationCompleted;
        
        private System.Threading.SendOrPostCallback deptDictOperationCompleted;
        
        private System.Threading.SendOrPostCallback outpOrderDispenseOperationCompleted;
        
        private System.Threading.SendOrPostCallback inpOrderDispenseOperationCompleted;
        
        private System.Threading.SendOrPostCallback drugDictOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DIHPMPFWebservice() {
            this.Url = global::BDSender.Properties.Settings.Default.BDSender_dih_webserv_DIHPMPFWebservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event wardDictCompletedEventHandler wardDictCompleted;
        
        /// <remarks/>
        public event pharmacyDictCompletedEventHandler pharmacyDictCompleted;
        
        /// <remarks/>
        public event inpOrderCompletionNotifyCompletedEventHandler inpOrderCompletionNotifyCompleted;
        
        /// <remarks/>
        public event staffDictCompletedEventHandler staffDictCompleted;
        
        /// <remarks/>
        public event outpOrderCompletionNotifyCompletedEventHandler outpOrderCompletionNotifyCompleted;
        
        /// <remarks/>
        public event deptDictCompletedEventHandler deptDictCompleted;
        
        /// <remarks/>
        public event outpOrderDispenseCompletedEventHandler outpOrderDispenseCompleted;
        
        /// <remarks/>
        public event inpOrderDispenseCompletedEventHandler inpOrderDispenseCompleted;
        
        /// <remarks/>
        public event drugDictCompletedEventHandler drugDictCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:wardDict", RequestNamespace="http://webservice.pmpf.dih.com", ResponseNamespace="http://webservice.pmpf.dih.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string wardDict([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("wardDict", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void wardDictAsync(string xml) {
            this.wardDictAsync(xml, null);
        }
        
        /// <remarks/>
        public void wardDictAsync(string xml, object userState) {
            if ((this.wardDictOperationCompleted == null)) {
                this.wardDictOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwardDictOperationCompleted);
            }
            this.InvokeAsync("wardDict", new object[] {
                        xml}, this.wardDictOperationCompleted, userState);
        }
        
        private void OnwardDictOperationCompleted(object arg) {
            if ((this.wardDictCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.wardDictCompleted(this, new wardDictCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:pharmacyDict", RequestNamespace="http://webservice.pmpf.dih.com", ResponseNamespace="http://webservice.pmpf.dih.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string pharmacyDict([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("pharmacyDict", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void pharmacyDictAsync(string xml) {
            this.pharmacyDictAsync(xml, null);
        }
        
        /// <remarks/>
        public void pharmacyDictAsync(string xml, object userState) {
            if ((this.pharmacyDictOperationCompleted == null)) {
                this.pharmacyDictOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpharmacyDictOperationCompleted);
            }
            this.InvokeAsync("pharmacyDict", new object[] {
                        xml}, this.pharmacyDictOperationCompleted, userState);
        }
        
        private void OnpharmacyDictOperationCompleted(object arg) {
            if ((this.pharmacyDictCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pharmacyDictCompleted(this, new pharmacyDictCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:inpOrderCompletionNotify", RequestNamespace="http://webservice.pmpf.dih.com", ResponseNamespace="http://webservice.pmpf.dih.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string inpOrderCompletionNotify([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("inpOrderCompletionNotify", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void inpOrderCompletionNotifyAsync(string xml) {
            this.inpOrderCompletionNotifyAsync(xml, null);
        }
        
        /// <remarks/>
        public void inpOrderCompletionNotifyAsync(string xml, object userState) {
            if ((this.inpOrderCompletionNotifyOperationCompleted == null)) {
                this.inpOrderCompletionNotifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OninpOrderCompletionNotifyOperationCompleted);
            }
            this.InvokeAsync("inpOrderCompletionNotify", new object[] {
                        xml}, this.inpOrderCompletionNotifyOperationCompleted, userState);
        }
        
        private void OninpOrderCompletionNotifyOperationCompleted(object arg) {
            if ((this.inpOrderCompletionNotifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.inpOrderCompletionNotifyCompleted(this, new inpOrderCompletionNotifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:staffDict", RequestNamespace="http://webservice.pmpf.dih.com", ResponseNamespace="http://webservice.pmpf.dih.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string staffDict([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("staffDict", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void staffDictAsync(string xml) {
            this.staffDictAsync(xml, null);
        }
        
        /// <remarks/>
        public void staffDictAsync(string xml, object userState) {
            if ((this.staffDictOperationCompleted == null)) {
                this.staffDictOperationCompleted = new System.Threading.SendOrPostCallback(this.OnstaffDictOperationCompleted);
            }
            this.InvokeAsync("staffDict", new object[] {
                        xml}, this.staffDictOperationCompleted, userState);
        }
        
        private void OnstaffDictOperationCompleted(object arg) {
            if ((this.staffDictCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.staffDictCompleted(this, new staffDictCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:outpOrderCompletionNotify", RequestNamespace="http://webservice.pmpf.dih.com", ResponseNamespace="http://webservice.pmpf.dih.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string outpOrderCompletionNotify([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("outpOrderCompletionNotify", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void outpOrderCompletionNotifyAsync(string xml) {
            this.outpOrderCompletionNotifyAsync(xml, null);
        }
        
        /// <remarks/>
        public void outpOrderCompletionNotifyAsync(string xml, object userState) {
            if ((this.outpOrderCompletionNotifyOperationCompleted == null)) {
                this.outpOrderCompletionNotifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnoutpOrderCompletionNotifyOperationCompleted);
            }
            this.InvokeAsync("outpOrderCompletionNotify", new object[] {
                        xml}, this.outpOrderCompletionNotifyOperationCompleted, userState);
        }
        
        private void OnoutpOrderCompletionNotifyOperationCompleted(object arg) {
            if ((this.outpOrderCompletionNotifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.outpOrderCompletionNotifyCompleted(this, new outpOrderCompletionNotifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:deptDict", RequestNamespace="http://webservice.pmpf.dih.com", ResponseNamespace="http://webservice.pmpf.dih.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string deptDict([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("deptDict", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void deptDictAsync(string xml) {
            this.deptDictAsync(xml, null);
        }
        
        /// <remarks/>
        public void deptDictAsync(string xml, object userState) {
            if ((this.deptDictOperationCompleted == null)) {
                this.deptDictOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeptDictOperationCompleted);
            }
            this.InvokeAsync("deptDict", new object[] {
                        xml}, this.deptDictOperationCompleted, userState);
        }
        
        private void OndeptDictOperationCompleted(object arg) {
            if ((this.deptDictCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deptDictCompleted(this, new deptDictCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:outpOrderDispense", RequestNamespace="http://webservice.pmpf.dih.com", ResponseNamespace="http://webservice.pmpf.dih.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string outpOrderDispense([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("outpOrderDispense", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void outpOrderDispenseAsync(string xml) {
            this.outpOrderDispenseAsync(xml, null);
        }
        
        /// <remarks/>
        public void outpOrderDispenseAsync(string xml, object userState) {
            if ((this.outpOrderDispenseOperationCompleted == null)) {
                this.outpOrderDispenseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnoutpOrderDispenseOperationCompleted);
            }
            this.InvokeAsync("outpOrderDispense", new object[] {
                        xml}, this.outpOrderDispenseOperationCompleted, userState);
        }
        
        private void OnoutpOrderDispenseOperationCompleted(object arg) {
            if ((this.outpOrderDispenseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.outpOrderDispenseCompleted(this, new outpOrderDispenseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:inpOrderDispense", RequestNamespace="http://webservice.pmpf.dih.com", ResponseNamespace="http://webservice.pmpf.dih.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string inpOrderDispense([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("inpOrderDispense", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void inpOrderDispenseAsync(string xml) {
            this.inpOrderDispenseAsync(xml, null);
        }
        
        /// <remarks/>
        public void inpOrderDispenseAsync(string xml, object userState) {
            if ((this.inpOrderDispenseOperationCompleted == null)) {
                this.inpOrderDispenseOperationCompleted = new System.Threading.SendOrPostCallback(this.OninpOrderDispenseOperationCompleted);
            }
            this.InvokeAsync("inpOrderDispense", new object[] {
                        xml}, this.inpOrderDispenseOperationCompleted, userState);
        }
        
        private void OninpOrderDispenseOperationCompleted(object arg) {
            if ((this.inpOrderDispenseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.inpOrderDispenseCompleted(this, new inpOrderDispenseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:drugDict", RequestNamespace="http://webservice.pmpf.dih.com", ResponseNamespace="http://webservice.pmpf.dih.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string drugDict([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("drugDict", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void drugDictAsync(string xml) {
            this.drugDictAsync(xml, null);
        }
        
        /// <remarks/>
        public void drugDictAsync(string xml, object userState) {
            if ((this.drugDictOperationCompleted == null)) {
                this.drugDictOperationCompleted = new System.Threading.SendOrPostCallback(this.OndrugDictOperationCompleted);
            }
            this.InvokeAsync("drugDict", new object[] {
                        xml}, this.drugDictOperationCompleted, userState);
        }
        
        private void OndrugDictOperationCompleted(object arg) {
            if ((this.drugDictCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.drugDictCompleted(this, new drugDictCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void wardDictCompletedEventHandler(object sender, wardDictCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class wardDictCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal wardDictCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void pharmacyDictCompletedEventHandler(object sender, pharmacyDictCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pharmacyDictCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pharmacyDictCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void inpOrderCompletionNotifyCompletedEventHandler(object sender, inpOrderCompletionNotifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class inpOrderCompletionNotifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal inpOrderCompletionNotifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void staffDictCompletedEventHandler(object sender, staffDictCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class staffDictCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal staffDictCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void outpOrderCompletionNotifyCompletedEventHandler(object sender, outpOrderCompletionNotifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class outpOrderCompletionNotifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal outpOrderCompletionNotifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void deptDictCompletedEventHandler(object sender, deptDictCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deptDictCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deptDictCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void outpOrderDispenseCompletedEventHandler(object sender, outpOrderDispenseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class outpOrderDispenseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal outpOrderDispenseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void inpOrderDispenseCompletedEventHandler(object sender, inpOrderDispenseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class inpOrderDispenseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal inpOrderDispenseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void drugDictCompletedEventHandler(object sender, drugDictCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class drugDictCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal drugDictCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591